name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
  
    - name: Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy as static site to the S3 bucket
      run: aws s3 sync build/ s3://${{ secrets.AWS_BUCKET_NAME }} --acl public-read
